spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        fund-raised: fund-raised-topic
        project-view-channel: project-view
        profile-view: profile-view-channel
        goal-completed: goal-completed-topic
        search-appearance-channel: search-appearance-topic
        follower: follower-channel
        comment-notification-channel: comment-topic

server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
